HWConfig:

    dma_cycles: 0.015625 # Calculated from our runs in AWS F1 instance in the hardware.
    # for depthwise in single, two, or three layer dataflow schedules
    hx: 0
    wx: 0
    cx: 0
    mac_wx: 0
    mac_wx_type: 0
    mac_cx: 0


    # for first pointwise in single, two layer or three layer dataflow schedules
    hxx: 15
    wxx: 15
    cxx: 8
    fx: 49
    mac_wxx: 0
    mac_wxx_type: 0
    mac_cxx: 0
    mac_fx: 0

    # for last pointwise layer in three layer cross-layer dataflow schedules
    hxx2: 13
    wxx2: 13
    cxx2: 8
    fx2: 49
    mac_wxx2: 0
    mac_wxx2_type: 0
    mac_cxx2: 0
    mac_fx2: 0