HWConfig:

    dma_cycles: 0.015625
#    # for depthwise
#    hx: 15
#    wx: 15
#    cx: 3
#    mac_wx: 2
#    mac_wx_type: 7
#    mac_cx: 0


    # for pointwise
    hxx: 15
    wxx: 15
    cxx: 7
    fx: 3
    mac_wxx: 1
    mac_wxx_type: 7
    mac_cxx: 0
    mac_fx: 0

#    # for pointwise
#    hxx2: 13
#    wxx2: 13
#    cxx2: 3
#    fx2: 7
#    mac_wxx2: 2
#    mac_wxx2_type: 7
#    mac_cxx2: 0
#    mac_fx2: 0